# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "${{ env.PACKAGE_ECOSYSTEM }}" # Autofilled based on the repository
    directory: "${{ env.PACKAGE_MANIFESTS_DIRECTORY }}" # Autofilled based on the repository
    schedule:
      interval: "${{ env.UPDATE_INTERVAL }}" # Autofilled based on the repository
    allow:
      - dependency-type: "all" # Allow updates for all types of dependencies
    automerge:
      - security-updates # Automatically merge security updates
      - non-breaking # Automatically merge non-breaking updates
    ignore:
      - dependency-name: "module-name-1" # Ignore specific dependencies from updates
      - dependency-name: "module-name-2"
    pin:
      - dependency-name: "module-name-3" # Pin specific dependencies to a version
      - dependency-name: "module-name-4"
      
    # Custom policies and rules
    policies:
      - package-ecosystem: "${{ env.PACKAGE_ECOSYSTEM }}" # Autofilled based on the repository
        directory: "${{ env.PACKAGE_MANIFESTS_DIRECTORY }}" # Autofilled based on the repository
        policy-rules:
          - update-all: false # Disable automatic updates for all dependencies within this ecosystem
          - match:
              dependency-name: "module-name-5"
              version-range: ">=2.0.0 <3.0.0" 
            update: false # Disable updates for a specific dependency version range within this ecosystem

          - match:
              dependency-name: "module-name-6"
              version-range: ">=1.5.0 <2.0.0"
            automerge: true # Automatically merge updates for a specific dependency version range within this ecosystem

    version-range-controls:
      - dependency-name: "module-name-7"
        version-range: "^1.0.0"

    security-policies:
      - dependency-name: "module-name-8"
        required-version: ">=1.2.0"
    
    automated-testing:
      - suite: "unit-tests"
        script: "npm run test:unit"
        on: "pull-request"
      
      - suite: "integration-tests"
        script: "npm run test:integration"
        on: "push"

    notifications:
      - type: "email"
        recipients: "dev-team@example.com"
        on: "update"
      
      - type: "slack"
        channel: "#dependencies"
        on: "security-update"

    audit-logs:
      - type: "dependency-update"
        store: "security-audit-logs"
    
    policy-enforcement:
      - type: "availability"
        apply-to: "dependencies"
        threshold: "99.9%"
    
    dependency-graph:
      - type: "network"
        depth: 3
